using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models;

/// <summary>
/// Represents a challenge entity.
/// </summary>
/// <remarks>
/// The Challenge class includes details about a specific challenge, such
/// as its name, description, weight category, and series.
/// </remarks>
public class Challenge
{
       /// <summary>
       /// Gets or sets the unique identifier for the challenge entity.
       /// </summary>
       /// <remarks>
       /// This property serves as the primary key and is auto-generated by the database.
       /// </remarks>
       [Key]
       [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
       public int Id { get; set; }

       /// <summary>
       /// Gets or sets the name of the challenge.
       /// </summary>
       /// <remarks>
       /// This property is required and must contain a non-null value.
       /// </remarks>
       [Required] public string Name { get; set; }

       /// <summary>
       /// Gets or sets the description of the challenge.
       /// </summary>
       /// <remarks>
       /// This property provides detailed information about the challenge.
       /// It is a required field and must be supplied when creating or updating a challenge.
       /// </remarks>
       [Required] public string Description { get; set; }

       /// <summary>
       /// Represents the weight category associated with the challenge.
       /// This property is required and categorizes the challenge based on weight.
       /// </summary>
       [Required] public string? WeightCategory { get; set; }

       /// <summary>
       /// Gets or sets the foreign key identifier for the related Serie entity.
       /// </summary>
       /// <remarks>
       /// This property establishes a relationship between the Challenge and Serie entities.
       /// It is mandatory and corresponds to the primary key of the related Serie entity.
       /// </remarks>
       [ForeignKey(nameof(Serie))]
       public int? SerieId { get; set; }

       /// <summary>
       /// Gets or sets the associated series entity for the challenge.
       /// </summary>
       /// <remarks>
       /// This property establishes a relationship between the Challenge and Serie entities, linking a challenge to its respective series.
       /// </remarks>
       public Serie? Serie { get; set; }
}