using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models;

/// <summary>
/// Represents a user session within the application, including authentication details, expiration, and user association.
/// </summary>
public class Session
{
       /// <summary>
       /// Gets the unique identifier for the session.
       /// This is the primary key for the session entity and is automatically generated by the database.
       /// </summary>
       [Key]
       [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
       public int Id { get; init; }

       /// <summary>
       /// Represents a unique token associated with a session for authentication or identification purposes.
       /// </summary>
       /// <remarks>
       /// The <c>Token</c> is a required property and serves as a unique identifier for the session.
       /// It is automatically managed and used within various authentication or session handling mechanisms.
       /// </remarks>
       [Required] public string Token { get; set; } = null!;

       /// <summary>
       /// Gets or sets the expiration date and time for the session.
       /// </summary>
       /// <remarks>
       /// This property represents the point in time when the session becomes invalid.
       /// It is required and must be set to a valid <see cref="DateTime"/> value.
       /// </remarks>
       [Required] public DateTime Expiration { get; set; }

       /// <summary>
       /// Represents the unique identifier of the user associated with the session.
       /// </summary>
       /// <remarks>
       /// This property serves as a foreign key referencing the <c>User</c> entity.
       /// It is marked as required, ensuring that every session is always linked to a valid user.
       /// </remarks>
       [ForeignKey(nameof(User))] [Required] public int UserId { get; set; }

       /// <summary>
       /// Represents a user in the system with associated information such as username, password,
       /// email, and an optional linked character.
       /// This class is used for managing user-related operations and relationships.
       /// </summary>
       public User User { get; set; } = null!;
}