using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models;

/// <summary>
/// Represents a user in the system with associated authentication and relationship data.
/// </summary>
public class User
{
    /// <summary>
    /// Gets the unique identifier for an instance of the User class.
    /// This property is automatically generated by the database upon creation,
    /// and serves as the primary key for the User entity.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; init; }

    /// <summary>
    /// Gets or sets the username of the user.
    /// This property is required and is used to uniquely identify the user
    /// within the application, such as during login or session management processes.
    /// </summary>
    [Required] public string Username { get; set; }

    /// <summary>
    /// Represents the password of the user.
    /// </summary>
    /// <remarks>
    /// This property is required and is used for authentication. The password is typically
    /// hashed before being stored in the database for security reasons.
    /// </remarks>
    [Required] public string Password { get; set; }

    /// <summary>
    /// User email
    /// </summary>
    [Required] public string Email { get; set; }

    /// <summary>
    /// Gets or sets the identifier of the associated Character entity.
    /// This property establishes a relationship between the User and Character entities
    /// is nullable to allow users without an associated character.
    /// </summary>
    [ForeignKey(nameof(Character))]
    public int? CharacterId { get; set; }

    /// <summary>
    /// Represents a character model in the data layer, containing properties related to character attributes.
    /// </summary>
    public Character? Character { get; set; }
}